### ISSUE TITLE
dragonite-forwarder客户端如何开机并在后台运行

### ISSUE THREAD

**Issue by Dakwu** [dragonite-network/dragonite-java#26]
用dragonite-forwarder加速SS,按照网上的方法将批处理文件加入开机启动但是不起作用, 还有如何在后台运行呢?老是有个窗口在这不舒服

**Comment by tobyxdd** [comment]
网上的什么方法？理论上是可以的 应该只是你操作问题
后台运行目前没有直接的办法 你可以试试用 ConEmu 之类的第三方命令行软件 有隐藏到系统托盘的功能

**Comment by Dakwu** [comment]
在组策略管理器中将脚本加入到 Windows Settings/Scripts/Startup 中, 我再试试其他方法吧
