### ISSUE TITLE
Optional reliability?

### ISSUE THREAD

**Issue by io7m** [dragonite-network/dragonite-java#28]
Hello!

I've been looking for a good reliable UDP library for the core of a multiplayer game engine for quite a while. I've made a few aborted efforts to develop my own, but I've run into algorithm issues each time for which I've not found any decent solutions. I'm therefore quite excited to have stumbled upon `dragonite-java`.

In a game engine, messages between the client and server don't need to be 100% reliable. In other words, some types of messages absolutely need to have reliable delivery (the game cannot continue unless the messages reach the destination), but other types of messages can be lost in transit without affecting the game too badly. An example of the former type would be player deaths: If a player dies, the game would be in an inconsistent state if not all players received the message that a player had died. An example of the latter type would be player position updates: Position updates are broadcast dozens of times per second. If a position update gets lost, there's no need to wait around for it to be re-sent as the next one will be along in a few milliseconds anyway.

My questions are:

1. Is it possible, in `dragonite`, to specify that I want some messages to be sent reliably and not others? 

2. If opt-in unreliability is supported, does the library preserve ordering for reliable and unreliable messages? In other words, if I send an unreliable message `M1` followed by a reliable message `M2`, does the library guarantee that I won't receive `M2` before `M1` (by discarding `M1` if `M2` has already been delivered)?

**Comment by tobyxdd** [comment]
Unfortunately dragonite currently does not support optional reliability. It's designed to provide reliability based on unreliable UDP protocol.
TBH I recommend you to try some other libraries like [KCP](https://github.com/skywind3000/kcp/blob/master/README.en.md) (not by me) for your real-time multiplayer games, as many design decisions I made for dragonite are for getting higher throughput, not lower latency.
Thanks for your attention to my project, hope everything works out well for your engine :)

**Comment by io7m** [comment]
OK, thanks!
