### ISSUE TITLE
[ERROR] Failed to parse config: java.nio.file.NoSuchFileException: server1.json

### ISSUE THREAD

**Issue by chengdu518** [dragonite-network/dragonite-java#33]
12:29:01(-04) [INFO] Dragonite Proxy Version: v0.3.1
12:29:01(-04) [INFO] SDK Version: v0.3.3
12:29:01(-04) [INFO] Mux Version: v0.3.0
12:29:01(-04) [INFO] Checking for updates...
12:29:03(-04) [INFO] ** New version available! v0.4.0 **
12:29:03(-04) [INFO] Using commandline arguments
12:29:03(-04) [ERROR] Failed to parse config: java.nio.file.NoSuchFileException: server1.json

**Comment by tobyxdd** [comment]
You sure that your configuration file is called server1.json & is in the correct path?

**Comment by chengdu518** [comment]
请问这个  server1.json 文件该放在什么地方呢

**Comment by chengdu518** [comment]
我又试着用命令参数配置，提示[ERROR] Unable to initialize: java.net.BindException: Address already in use (Bind failed)
