### ISSUE TITLE
在dragonite-sdk遇到一个问题

### ISSUE THREAD

**Issue by JeremieCHN** [dragonite-network/dragonite-java#41]
我用这个库作为一个RUDP来用，在使用过程中偶然遇到了一个情况，在我多个线程同时用同一个DragointeSocket发包的时候，一直卡在了`SandHanlder类`中的一个同步块中   
```JAVA
protected void sendDataMessage_noSplit(final byte[] data) {
   // ........省略了一部分
            synchronized (state.sendWindowLock) {   
                while (!receiveHandler.checkWindowAvailable() && canSend()) {   
                    state.sendWindowLock.wait();   
                }   
            }   
   // ........省略了一部分code   
    }
```
我发现我有一个线程一直在这个同步块中出不来，麻烦的是这个情况不能稳定复现，于是我直接在wait()前面加了一句notifyAll，`state.sendWindowLock.notifyAll();`这样之后虽然短时间内没有再出现这个问题，但是我觉得可能是我在使用这个库的时候用法不对，所以想请教一下大大

**Comment by tobyxdd** [comment]
谢谢反馈 我再检查下线程同步的问题

你添加 `state.sendWindowLock.notifyAll();` 除了会让其他发送线程多跑几次 `checkWindowAvailable()` 和 `canSend()` 倒也不会有其他副作用。如果把多个发送线程改为向一个队列添加数据，单线程负责发送还会出现这种情况吗？

**Comment by JeremieCHN** [comment]
这个不清楚，我试一下，我现在又写了一个`send()`方法，加了`synchronized`关键字，然后所有的线程都通过这个方法来调用发包，但是也没有效果，我用你说的方法试试看
```java
 synchronized void send(Message msg) throws InterruptedException, IncorrectSizeException, IOException,SenderClosedException {
            dSocket.send(msg.toBytes());
    }
```

**Comment by JeremieCHN** [comment]
用你说的方法解决问题了，看来是只在多个线程同时调用的时候才可能触发这个问题，单线程高频率的调用是可以的，非常感谢你的回复
