### ISSUE TITLE
Is dragonite suitable for game server ?

### ISSUE THREAD

**Issue by medusar** [dragonite-network/dragonite-java#42]
I have been writing a game server based on [KCP](https://github.com/skywind3000/kcp), and today i find this project.
The performance diagram shows that it performs better than KCP and TCP BBR, so i am thinking about using this as an alternative to KCP for my game server.

**Comment by tobyxdd** [comment]
It depends on the type of your game. Is it a real-time multiplayer game?

**Comment by medusar** [comment]
@tobyxdd Yes, it is a real-time multiplayer game, and it is sensitive to delay.

**Comment by tobyxdd** [comment]
Then you shouldn't use dragonite. In fact, you shouldn't TCP or KCP either. These are all reliable protocols with retransmission mechanisms to ensure the integrity of the data, which means there will be huge latency spikes when a retransmission occurs. Real-time multiplayer games usually sync the states 30-60 times every second (tick rate) so they don't need the underlying protocol to be reliable, as a few lost packets won't have any serious effect.

**Comment by medusar** [comment]
@tobyxdd Yes, in theory, we should use UDP instead of TCP. It seems that KCP work fine for some real-time games, so i think maybe i can optimize KCP with some good ideas from dragonite.
