### ISSUE TITLE
Feature req: traffic obfuscation

### ISSUE THREAD

**Issue by kuzhao** [dragonite-network/dragonite-java#8]
Can we possibly have a built-in obfuscator so that traffic patterns could be reshaped before transmitted?

**Comment by tobyxdd** [comment]
All packets are encrypted with AES if you turn on encryption, so I would say the payload itself should have no special "pattern". Theoretically, it's possible to detect Dragonite by the traffic patterns. But it should be hard, and we simply can't create any counter-measure before any effective measure comes out first 😆 

Our SDK has a PacketCryptor (https://github.com/dragonite-network/dragonite-java/blob/master/dragonite-sdk/src/main/java/com/vecsight/dragonite/sdk/cryptor/PacketCryptor.java) interface which makes implementing traffic encryptions & obfuscations a relatively simple task. If your network has special requirements for Dragonite to work properly, consider implementing your own PacketCryptor.
